# Generated by Django 6.0.4 on 2026-06-03 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0010_buraco_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='buraco',
            index=models.Index(fields=['-created_at'], name='buraco_created_idx'),
        ),
        migrations.AddIndex(
            model_name='buraco',
            index=models.Index(fields=['status', '-created_at'], name='buraco_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='buraco',
            index=models.Index(fields=['usuario', '-created_at'], name='buraco_usuario_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['buraco', 'resposta_de', 'created_at'], name='coment_buraco_resp_idx'),
        ),
    ]
