# Generated by Django 6.0.4 on 2026-06-03 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0011_buraco_buraco_created_idx_and_more'),
        ('principal', '0003_alter_notificacao_tipo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida', '-created_at'], name='notif_dest_lida_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', '-created_at'], name='notif_dest_created_idx'),
        ),
    ]
